name: CI
on: [push, pull_request]
jobs:
  build:
    timeout-minutes: 5
    name: Build, lint, & test lib
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
            /home/runner/.cache/Cypress
            C:\Users\runneradmin\AppData\Local\Cypress\Cache
            **/.next/cache
          key: ${{ runner.os }}-${{ runner.node_version}}-yarn-v4-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.node_version}}-yarn-v4-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --silent --ignore-scripts
        env:
          CI: true

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: 9d1ce86d55b91864d3cf11c712add541a32587ee2e05da054cb16629f7a6f090
        with:
          coverageCommand: echo coverage
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov

  nextjs-example:
    name: Build Next.js Example
    defaults:
      run:
        working-directory: examples/next.js
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
            /home/runner/.cache/Cypress
            C:\Users\runneradmin\AppData\Local\Cypress\Cache
            **/.next/cache
          key: ${{ runner.os }}-${{ runner.node_version}}-yarn-nextjs-example-v4-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.node_version}}-yarn-nextjs-example-v4-

      - name: Install
        run: |
          yarn --silent --frozen-lockfile
        env:
          CI: true

      - name: Build
        run: yarn build
