name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build, lint, & test lib

    continue-on-error: true
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        node: ['10', '12', '14', '16']
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --coverage --maxWorkers=2

      - name: Build
        run: yarn build

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: 9d1ce86d55b91864d3cf11c712add541a32587ee2e05da054cb16629f7a6f090
        with:
          coverageCommand: echo coverage
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov

  nextjs-example:
    name: Build Next.js Example
    defaults:
      run:
        working-directory: examples/next.js
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build
